We can think of the keypresses as making a queue. In general, we can
imagine that on keydown, a key is added to the queue (on the right
side) and that on keyup, the key is removed from the queue. Things
will be slightly different for this implementation though:

* Keydown
The key is added to the queue and Queue Cleanup is run.
* Keyup
** asdfjkl;
The key or the corresponding modifierqueue and the keypress is immediately sent to the OS on keydown. if
the queue is not empty, then the key is added to the queue and a
keypress is not yet registered. So that's everything that happens on
keydown. If none of asdfjkl; are in the queue, then when a key is
added, the keypress is sent to the OS on keydown (when the key is
added to the queue). If any of asdfjkl; are in the queue, then when a
key is added, the keypress is not sent to the OS until one of two
things happen. First, if the next key to be remove from the
* Queue Cleanup
Any non-a/s/d/f/j/k/l/;/space keys at the output end of the queue are
popped from the queue.

